### ISSUE TITLE
Japanese morphological analysis

### ISSUE THREAD

**Issue by AerisNyx** [DennisMerkus/Quenya#5]
# Tasks
- [ ] Create a rudimentary dictionary with the required data
- [ ] Create a set of affixes for Japanese that should be looked for
- [ ] Create a set of particles for Japanese that signify word boundaries
- [ ] Write an algorithm that determines word boundaries by using the dictionary, affixes, particles and punctuation

# Algorithm

Go over text, looking ahead and back.
Check for common conjugation patterns, such as して, います, etc. These are associated with a small number of verb/noun forms. Check whether they appear before these patterns. If so, we can combine them into a verb token and set the word boundary.
Check for particles, such as の, を, etc, and check if it could work as a word boundary (i.e., these characters are not part of the previous/next word).
When a word is found, check whether it can be extended into a compound word. If so, add both options as word candidates in the sentence paths graph.

## Notes for Language-Agnostic/general parsing

- We're looking to recognize all possible 'paths' that a sentence's words can be put together.
- Affixes should be cached/quickly referenced to make continuous checking easier. Especially for languages like Japanese and Chinese without white-space word boundaries.
